#!/usr/bin/env python3
"""Generate docs/registry/source-register.md from data/source_register.csv.

Canonical source enforcement: the CSV is the single source of truth. The
markdown page is a derived artifact. Never hand-edit the output; edit the
CSV and re-run this tool, then refresh the drift manifest. stdlib only.
"""
from __future__ import annotations

import csv
from pathlib import Path

HEADER = """# Source register

!!! note "Derived artifact"
    Generated by `tools/generate_register_page.py` from
    `data/source_register.csv`. Do not hand-edit. The drift gate fails CI
    if this page and the CSV disagree.

Thirty-two public artifacts. Tier meanings: VERIFIED, CORROBORATED,
UNCORROBORATED, INFERENCE, STATED. Firm self-claims are always STATED and
never promoted without independent confirmation. FLAG in notes marks
recency-window edges or historical records retained per the QA ledger.

"""

FOOTER = """
Reliability follows Admiralty convention: A1 official public records,
B1 the target firm's own published artifacts (structure verifiable,
self-claims quarantined), B2 corporate secondary channels.

BHIL, STENCIL v1.0. Human-Directed. AI-Enabled. Commercially Tested.
"""


def escape(cell: str) -> str:
    """Escape pipes so titles cannot break the markdown table."""
    return cell.replace("|", "\\|")


def build(csv_path: Path) -> str:
    with csv_path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    lines = [HEADER]
    for taxonomy, label in [
        ("T1", "T1: Thought leadership"),
        ("T2", "T2: Case studies"),
        ("T3", "T3: Presentations and webinars"),
        ("T4", "T4: Frameworks and models"),
        ("T5", "T5: Procurement records"),
        ("T6", "T6: Data visualizations"),
    ]:
        subset = [r for r in rows if r["taxonomy"].split("/")[0] == taxonomy]
        lines.append(f"## {label} ({len(subset)})\n")
        lines.append("| ID | Artifact | Date | Locator | Sweep | Access | Tier |")
        lines.append("| --- | --- | --- | --- | --- | --- | --- |")
        for r in subset:
            note = f" `{escape(r['notes'])}`" if r["notes"].strip() else ""
            lines.append(
                "| {id} | {title}{note} | {date} | `{locator}` | {discovery} | {access} | {tier} |".format(
                    id=r["id"],
                    title=escape(r["title"]),
                    note=note,
                    date=escape(r["date"]),
                    locator=escape(r["locator"]),
                    discovery=r["discovery"],
                    access=r["access"],
                    tier=r["tier"],
                )
            )
        lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    out = root / "docs" / "registry" / "source-register.md"
    out.write_text(build(root / "data" / "source_register.csv"), encoding="utf-8")
    print(f"wrote {out.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
